/* ============================================================================
 * Post
 * ============================================================================
 * A Post is the atomic, publishable unit of content.
 * Posts appear in feeds and may also be used as Project entries and Album entries.
 */


/* --------------------------------------------------------------------------
 * Visibility:
    -public: everyone can see
    -private: only you can see
    -restricted: restricted to the people you choose
 * -------------------------------------------------------------------------- */

export type PostVisibility = "public" | "private" | "restricted";

/* --------------------------------------------------------------------------
 * Post
 * -------------------------------------------------------------------------- */

export interface TextPost {
  id: string;
  slug: string;

  title?: string; 
  tags?: string[];

  visibility: PostVisibility;

  content: string; //Markdown

  createdAt: string;
  // updatedAt?: (autogenerated)
}